# AWS credentials
aws_region: us-east-1
secret_key: (secret_key)
access_key: (access_key)
#
aws_keypair: (aws_keypair_name)
ansible_ssh_private_key_file: (ssh_key_name.pem)

# MySQL credentials
mysql_user: admin
mysql_password: 1nsecure